# Autogenerated wrapper script for MINE_jll for x86_64-linux-gnu
export libmine

JLLWrappers.@generate_wrapper_header("MINE")
JLLWrappers.@declare_library_product(libmine, "libmine.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmine,
        "lib\\libmine.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
